### ISSUE TITLE
Unable to create pretty reports

### ISSUE THREAD

**Issue by skAutomation12** [damianszczepanik/cucumber-sandwich#71]
> `net.masterthought.cucumber.ValidationException: File 'target/cucumber-reports/cucumber.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:99)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:71)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:88)`

I am currently using     <cucumber-reporting>4.7.0</cucumber-reporting>
<cucumber.version>4.3.1</cucumber.version>

Below is the plugin setup in runner class
` plugin = {"json:target/cucumber-reports/cucumber.json",
                "pretty",
                "html:target/cucumber-reports/cucumber-pretty.html",`

**Comment by damianszczepanik** [comment]
Error message says what's wrong with the input file
